### ISSUE TITLE
Data types included, priority and placement

### ISSUE THREAD

**Issue by rankishore** [WormBase/genedesc_generator#19]
The following data types are included (number indicates placement in the gene description) for C. elegans genes:

1. Orthology to human 
2. GO molecular function
3. GO biological process
4. GO cellular component
5. Whether experimentally used to study disease or implication of human ortholog in diseases (via orthology)
6. Tissue expression

For information poor genes  (number indicates priority order for data type)

1. GO molecular function of human ortholog
2. Protein domains
3. Expression cluster data

The following data types are included for non-elegans genes:

1. Orthology to elegans or other species
2. Predicted MF, BP and CC annotations
3. When no GO information present, orthologous gene BP annotations in C. elegans
4.

**Comment by valearna** [comment]
Need to test if the workflow matches the descriptions
