### ISSUE TITLE
Include chemical regulation only for information poor genes

### ISSUE THREAD

**Issue by rankishore** [WormBase/genedesc_generator#22]
For information-poor C. elegans and brugia malayi genes only-
Template:
\<gene name\> is affected by \<count of chemicals\> chemicals based on \<method1\>, \<method2\> and \<method3/> study (studies).

Placement is always after expression pattern and Anatomy and Gene regulation sentences (when present).

Files to be used:
molReg files at ftp://caltech.wormbase.org/pub/wormbase/ExprClusterSummary/WS269/

**Comment by rankishore** [comment]
I don't see any chemical regulation expression cluster data in the WS269 pre-release file, 10-29-2018.

**Comment by valearna** [comment]
Duplicate of #27. Closing

**Comment by valearna** [comment]
Template Change:

For information-poor C. elegans and brugia malayi genes only-
Template:
1. when less than 4 chemicals:
<gene name> is affected by \<chemical 1\>, \<chemical 2\>, and \<chemical 3\> based on <method1>, <method2> and <method3/> studies
2. when more than 3 chemicals:
<gene name> is affected by <count of chemicals> chemicals including \<chemical 1\>, \<chemical 2\>, and \<chemical 3\> based on <method1>, <method2> and <method3/> studies.
pick the first 3 chemicals in the file. In the future we might need a better way to sort them
