### ISSUE TITLE
create new script to generate xml page for J to index directories and files

### ISSUE THREAD

**Issue by valearna** [WormBase/genedesc_generator#33]
the structure of the file has to be the same as the xml index page on the amazon S3 bucket, so that J can crawl the files in the same way. We can add an additional field with the up-to-date list of species

**Comment by valearna** [comment]
The file is ready for testing: http://textpressocentral.org:8083/WB/index.xml
This is the script to generate it: https://github.com/WormBase/genedesc_generator/blob/master/wormbase/create_index_file.py

**Comment by azurebrd** [comment]
Just J, not JC :) 

Waiting for people to sign off on the 3001 changes to go live, so I can modify it for textpresso / 3002 without having to merge potential changes if AGR people want them.

**Comment by valearna** [comment]
Cool, thanks @azurebrd - There's no rush, I just wanted to add you to this conversation to keep track of the issue

**Comment by valearna** [comment]
It looks like the index file is working. I've been monitoring it for the last couple of releases and every time I update the index with new files I see them in the diff tool.
